name: 抖音火山版

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 22,23,0-15 * * *'
  watch:
    types: started
  repository_dispatch:
    types: huoshan
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: xuxiaobo4510/APPSIGN
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行 【抖音火山版】'
        if: env.HSHEADER
        run: |
          node task/huoshan.js
        env:
          HSHEADER: ${{ secrets. HSHEADER }}
          HSBODY: ${{ secrets. HSBODY }}
          HSURL: ${{ secrets. HSURL }}
          PLAYBODY: ${{ secrets. PLAYBODY }}
          PLAYHEADER: ${{ secrets. PLAYHEADER }}
          PLAYURL: ${{ secrets. PLAYURL }}
